[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_ft = ['git', 'snippet', 'toml', 'vim', 'ruby']
hook_add = '''
source $XDG_CONFIG_HOME/plugins/asyncomplete.vim.rc.vim
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
on_ft = ['git', 'snippet', 'toml', 'vim', 'ruby']
hook_source = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
      \ 'name': 'buffer',
      \ 'priority': 5,
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#buffer#completor'),
      \ }))
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
on_ft = ['git', 'snippet', 'toml', 'vim', 'ruby']
hook_source = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
      \ 'name': 'file',
      \ 'priority': 3,
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#file#completor'),
      \ }))
'''


[[plugins]]
repo = 'Shougo/neco-syntax'
depends = ['asyncomplete.vim']
on_i = 1
hook_post_source = '''
let g:necosyntax#min_keyword_length = 1
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necosyntax.vim'
on_ft = ['git', 'snippet', 'toml', 'vim', 'ruby']
depends = ['neco-syntax']
hook_source = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#necosyntax#get_source_options({
      \ 'name': 'necosyntax',
      \ 'priority': 7,
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#necosyntax#completor'),
      \ }))
'''

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['asyncomplete.vim']
on_i = 1

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necovim.vim'
on_ft = ['vim']
depends = ['neco-vim']
hook_source = '''
autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#necovim#get_source_options({
      \ 'name': 'necovim',
      \ 'allowlist': ['vim'],
      \ 'priority': 10,
      \ 'completor': function('asyncomplete#sources#necovim#completor'),
      \ }))
'''

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# on_i = 1
# hook_add = '''
# source $XDG_CONFIG_HOME/plugins/neosnippet.rc.vim
# '''
#
# [[plugins]]
# repo = 'Shougo/neosnippet'
# on_i = 1
# depends = ['neosnippet-snippets']
#
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
# on_ft = ['git', 'snippet', 'toml', 'vim', 'ruby']
# depends = ['neosnippet.vim']
# hook_source = '''
# autocmd MyAutoCmd User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#neosnippet#get_source_options({
#       \ 'name': 'neosnippet',
#       \ 'allowlist': ['*'],
#       \ 'priority': 9,
#       \ 'completor': function('asyncomplete#sources#neosnippet#completor'),
#       \ }))
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-ultisnips.vim'
if = 'has("python3")'
on_i = 1
depends = ['ultisnips', 'asyncomplete.vim']
hook_source = '''
call asyncomplete#register_source(asyncomplete#sources#ultisnips#get_source_options({
    \ 'name': 'ultisnips',
    \ 'allowlist': ['*'],
    \ 'completor': function('asyncomplete#sources#ultisnips#completor'),
    \ }))
'''

[[plugins]]
repo = 'honza/vim-snippets'
# snippets ファイルだけを使うので runtimepath へ追加しない
rtp = ''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['ruby']
depends = ['asyncomplete.vim', 'vim-lsp']

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_add = '''
source $XDG_CONFIG_HOME/plugins/emmet-vim.rc.vim
'''

[[plugins]]
repo = "alvan/vim-closetag"
on_i = 1
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-closetag.rc.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'maralla/vim-toml-enhance'
on_ft = 'toml'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-toml-enhance.rc.vim
'''

[[plugins]]
repo = "kana/vim-smartinput"
on_i = 1

[[plugins]]
repo = "cohama/vim-smartinput-endwise"
on_i = 1
hook_post_source = '''
source $XDG_CONFIG_HOME/plugins/vim-smartinput-endwise.rc.vim
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
source $XDG_CONFIG_HOME/plugins/vim-markdown.rc.vim
'''

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown','mkd']

# [[plugins]]
# repo = 'kannokanno/previm'
# on_ft = ['markdown','mkd', 'textile']
# hook_add = '''
# source $XDG_CONFIG_HOME/plugins/previm.rc.vim
# '''

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['markdown','mkd']

[[plugins]]
repo = 'rytkmt/vim-textile'
on_ft = 'textile'

[[plugins]]
repo = 'thinca/vim-prettyprint'
on_ft = 'vim'

# [[plugins]]
# repo = 'itmammoth/run-rspec.vim'
# on_ft = 'ruby'

# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# if = 'has("nvim")'
# rev = 'next'
# build = 'bash install.sh'
# on_ft = 'ruby'
# hook_add = '''
# source $XDG_CONFIG_HOME/plugins/LanguageClient-neovim.rc.vim
# '''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim") && has("python3_compiled")'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/denite.nvim.rc.vim
'''
on_cmd = 'Denite'
hook_post_source = '''
source $XDG_CONFIG_HOME/plugins/denite.nvim.source.rc.vim
'''

[[plugins]]
repo = 'ujihisa/quicklearn'
on_ft = 'ruby'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/quicklearn.rc.vim
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = 'markdown'
build = 'sh -c "cd app && yarn install"'
hook_add = '''
source $XDG_CONFIG_HOME/plugins/markdown-preview.nvim.rc.vim
'''
